# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configurations are located in `/home/joey/.config/ygofab/config.toml`.

[expansion.ygofab-custom]
default = true
recipe = ['ygofab-custom.toml']

[picset.regular]
# default = true
mode = 'proxy'
size = '256x'
ext = 'png'
field = true

[picset.anime]
default = true
mode = 'anime'
size = '256x'
ext = 'png'
field = true
