[[card]]
id = 92384675
name = "Vylett, Underlord of Dark World"
type = "monster effect link"
setcode = 0x6
link-rating = 2
link-arrows = "bottom_left bottom_right"
attribute = "Dark"
race = "Fiend"
atk = 2100
effect = '''2 "Dark World" monsters
If this card is Link Summoned: Draw 2 cards, then discard 1 "Dark World" monster, or, if you do not have any in your hand, banish your entire hand. You can only use this effect of "Vylett, Underlord of Dark World" once per turn. Once per turn, at the start of the Damage Step, if this card attacks: You can add 1 "Dark World" monster from your Graveyard to your hand. Once per turn, at the start of the Damage Step, if a "Dark World" monster this card points to attacks: You can discard 1 card.'''
ot = "OCG TCG"
category = "draw banish send_to_hand destroy_hand"

[[card]]
id = 92384676
name = "Dark World Vengeance"
type = "trap continuous"
setcode = 0x6
effect = '''Once per turn, if exactly 1 face-up "Dark World" monster you control (and no other cards) would be destroyed: You can return that monster to the hand instead, and if you do, discard 1 card.'''
ot = "OCG TCG"
category = "send_to_hand destroy_hand"
